# Read RMF table

In [1]:
import pandas as pd
import numpy as np
RFM = pd.read_csv('RMF_table.csv')

In the following section, for the purpose of segmentation [Champions, Loyal, Big Spenders, At Risk, Lost], I give a score to each customer for each RMF feature based on quantile analysis. `RMF_score = 532` means the customer got `R_score = 5`, `M_score = 3`, and `Frequency_score = 2`. For the Frequency and Recency features, since their values are discrete, I ranked all data entries. Customers with identical values received the same average rank, ensuring that tied values are treated equally. Imagine that you have 100 data entries with `frequency=1`. If you use quantile-based scoring, you would give different `frequency_score` to different customers, although they have the same value. So that is why I came up with this approach of ranking.

In [2]:
# RFM['R_score'] = pd.qcut(RFM['Recency_Days'], 5, labels=[5,4,3,2,1])
rec_pct = RFM['Recency_Days'].rank(method='average', pct=True)
RFM['R_score'] = (6 - np.ceil(rec_pct*5)).astype(int).clip(1,5)


# RFM['Frequency_score'] = pd.qcut(RFM['Frequency'].rank(method = 'first'), 5, labels=[1,2,3,4,5])
freq_pct = RFM['Frequency'].rank(method = 'average', pct = True)
RFM['F_score'] = np.ceil(freq_pct * 5).astype(int).clip(1,5)

RFM['M_score'] = pd.qcut(RFM['Monetary'], 5, labels=[1,2,3,4,5])

RFM['RFM_score'] = RFM['R_score'].astype(str) + RFM['F_score'].astype(str) + RFM['M_score'].astype(str)
display(RFM.head())

,CustomerID,Recency_Days,Frequency,Monetary,R_score,F_score,M_score,RFM_score
0,12346.0,325.0,12,77556.46,2,5,5,255
1,12347.0,2.0,8,5633.32,5,4,5,545
2,12348.0,75.0,5,2019.40,3,4,4,344
3,12349.0,18.0,4,4428.69,5,3,5,535
4,12350.0,310.0,1,334.40,2,1,2,212

Now we can segment customers based on the RFM_score.

In [3]:
def segment_customer(row):
    if row['R_score'] >= 4 and row['F_score'] >= 4 and row['M_score'] >= 4:
        return 'Champions'
    elif row['F_score'] >= 4 and row['R_score'] >= 3:
        return 'Loyal'
    elif row['M_score'] >= 4:
        return 'Big Spenders'
    elif row['R_score'] <= 2 and row['F_score'] >= 3:
        return 'At Risk'
    elif row['R_score'] <= 2 and row['F_score'] <= 2:
        return 'Lost'
    else:
        return 'Need Attention'

RFM['Segment'] = RFM.apply(segment_customer, axis=1)
display(RFM.head(50))

,CustomerID,Recency_Days,Frequency,Monetary,R_score,F_score,M_score,RFM_score,Segment
0,12346.0,325.0,12,77556.46,2,5,5,255,Big Spenders
1,12347.0,2.0,8,5633.32,5,4,5,545,Champions
2,12348.0,75.0,5,2019.40,3,4,4,344,Loyal
3,12349.0,18.0,4,4428.69,5,3,5,535,Big Spenders
4,12350.0,310.0,1,334.40,2,1,2,212,Lost
5,12351.0,375.0,1,300.93,2,1,2,212,Lost
6,12352.0,36.0,10,2849.84,4,5,4,454,Champions
7,12353.0,204.0,2,406.76,2,2,2,222,Lost
8,12354.0,232.0,1,1079.40,2,1,3,213,Lost
9,12355.0,214.0,2,947.61,2,2,3,223,Lost
10,12356.0,22.0,6,6373.68,4,4,5,445,Champions
11,12357.0,33.0,3,18287.66,4,3,5,435,Big Spenders
12,12358.0,1.0,5,3887.07,5,4,5,545,Champions
13,12359.0,57.0,10,8935.94,4,5,5,455,Champions
14,12360.0,52.0,8,4252.89,4,4,5,445,Champions
15,12361.0,287.0,4,511.25,2,3,2,232,At Risk
16,12362.0,3.0,11,5356.23,5,5,5,555,Champions
17,12363.0,109.0,2,552.00,3,2,2,322,Need Attention
18,12364.0,7.0,4,1313.10,5,3,4,534,Big Spenders
19,12365.0,291.0,2,641.38,2,2,3,223,Lost
20,12366.0,633.0,1,500.24,1,1,2,112,Lost
21,12367.0,4.0,1,168.90,5,1,1,511,Need Attention
22,12368.0,628.0,1,917.70,1,1,3,113,Lost
23,12369.0,413.0,3,1791.15,1,3,4,134,Big Spenders
24,12370.0,51.0,7,4320.31,4,4,5,445,Champions
25,12371.0,44.0,5,4067.38,4,4,5,445,Champions
26,12372.0,71.0,3,1298.04,3,3,4,334,Big Spenders
27,12373.0,311.0,3,1127.65,2,3,3,233,At Risk
28,12374.0,25.0,4,2989.22,4,3,5,435,Big Spenders
29,12375.0,10.0,2,457.50,5,2,2,522,Need Attention
30,12376.0,389.0,2,503.15,2,2,2,222,Lost
31,12377.0,315.0,4,3426.32,2,3,5,235,Big Spenders
32,12378.0,129.0,2,5416.32,3,2,5,325,Big Spenders
33,12379.0,81.0,4,1620.22,3,3,4,334,Big Spenders
34,12380.0,21.0,11,9676.30,4,5,5,455,Champions
35,12381.0,4.0,5,1845.31,5,4,4,544,Champions
36,12383.0,184.0,5,1850.56,3,4,4,344,Loyal
37,12384.0,28.0,2,585.27,4,2,2,422,Need Attention
38,12385.0,379.0,1,1938.40,2,1,4,214,Big Spenders
39,12386.0,337.0,2,660.80,2,2,3,223,Lost
40,12387.0,415.0,1,143.94,1,1,1,111,Lost
41,12388.0,15.0,8,3901.11,5,4,5,545,Champions
42,12389.0,402.0,3,1433.33,2,3,4,234,Big Spenders
43,12390.0,79.0,1,549.84,3,1,2,312,Need Attention
44,12391.0,21.0,6,2773.42,4,4,4,444,Champions
45,12392.0,591.0,1,234.75,1,1,1,111,Lost
46,12393.0,72.0,6,2399.45,3,4,4,344,Loyal
47,12394.0,63.0,2,1272.48,3,2,4,324,Big Spenders
48,12395.0,19.0,15,5067.27,4,5,5,455,Champions
49,12396.0,674.0,1,931.43,1,1,3,113,Lost

Now let us visualize the segmented groups:

In [4]:
segment_summary = RFM.groupby('Segment').agg({
    'CustomerID': 'count',
    'Recency_Days': 'mean',
    'Frequency': 'mean',
    'Monetary': 'mean'
}).rename(columns={'CustomerID':'Count'}).sort_values('Count', ascending=False)

display(segment_summary)

                Count  Recency_Days  Frequency     Monetary
Segment
Lost             1571    457.184596   1.289624   341.842400
Need Attention   1358     61.231959   2.152430   537.796673
Champions        1271     19.151849  17.361133  9490.649477
Big Spenders      689    235.303338   4.946299  3347.408222
Loyal             606     85.722772   8.349835  2988.394546
At Risk           386    368.484456   3.865285   767.150363

In [12]:
segment_summary.to_csv("Segmented_customers.csv", index=True)
segment_summary.to_excel("Segmented_customers.xlsx", index=True)