# Read RMF table

In [ ]:
import pandas as pd
import numpy as np
RFM = pd.read_csv('RMF_table.csv')

In the following section, for the purpose of segmentation [Champions, Loyal, Big Spenders, At Risk, Lost], I give a score to each customer for each RMF feature based on quantile analysis. `RMF_score = 532` means the customer got `R_score = 5`, `M_score = 3`, and `Frequency_score = 2`. For the Frequency and Recency features, since their values are discrete, I ranked all data entries. Customers with identical values received the same average rank, ensuring that tied values are treated equally. Imagine that you have 100 data entries with `frequency=1`. If you use quantile-based scoring, you would give different `frequency_score` to different customers, although they have the same value. So that is why I came up with this approach of ranking.

In [3]:
# RFM['R_score'] = pd.qcut(RFM['Recency_Days'], 5, labels=[5,4,3,2,1])
rec_pct = RFM['Recency_Days'].rank(method='average', pct=True)
RFM['R_score'] = (6 - np.ceil(rec_pct*5)).astype(int).clip(1,5)


# RFM['Frequency_score'] = pd.qcut(RFM['Frequency'].rank(method = 'first'), 5, labels=[1,2,3,4,5])
freq_pct = RFM['Frequency'].rank(method = 'average', pct = True)
RFM['F_score'] = np.ceil(freq_pct * 5).astype(int).clip(1,5)

RFM['M_score'] = pd.qcut(RFM['Monetary'], 5, labels=[1,2,3,4,5])

RFM['RFM_score'] = RFM['R_score'].astype(str) + RFM['F_score'].astype(str) + RFM['M_score'].astype(str)
display(RFM.head())

,CustomerID,Recency_Days,Frequency,Monetary,R_score,F_score,M_score,RFM_score
0,12346.0,164.0,11,372.86,2,5,2,252
1,12347.0,2.0,2,1323.32,5,3,4,534
2,12348.0,73.0,1,222.16,2,1,1,211
3,12349.0,42.0,3,2671.14,3,3,5,335
4,12351.0,10.0,1,300.93,5,1,2,512

Now we can segment customers based on the RFM_score.

In [5]:
def segment_customer(row):
    if row['R_score'] >= 4 and row['F_score'] >= 4 and row['M_score'] >= 4:
        return 'Champions'
    elif row['F_score'] >= 4 and row['R_score'] >= 3:
        return 'Loyal'
    elif row['M_score'] >= 4:
        return 'Big Spenders'
    elif row['R_score'] <= 2 and row['F_score'] >= 3:
        return 'At Risk'
    elif row['R_score'] <= 2 and row['F_score'] <= 2:
        return 'Lost'
    else:
        return 'Need Attention'

RFM['Segment'] = RFM.apply(segment_customer, axis=1)
display(RFM.head(50))

,CustomerID,Recency_Days,Frequency,Monetary,R_score,F_score,M_score,RFM_score,Segment
0,12346.0,164.0,11,372.86,2,5,2,252,At Risk
1,12347.0,2.0,2,1323.32,5,3,4,534,Big Spenders
2,12348.0,73.0,1,222.16,2,1,1,211,Lost
3,12349.0,42.0,3,2671.14,3,3,5,335,Big Spenders
4,12351.0,10.0,1,300.93,5,1,2,512,Need Attention
5,12352.0,10.0,2,343.80,5,3,2,532,Need Attention
6,12353.0,43.0,1,317.76,3,1,2,312,Need Attention
7,12355.0,202.0,1,488.21,1,1,2,112,Lost
8,12356.0,15.0,3,3562.25,4,3,5,435,Big Spenders
9,12357.0,23.0,2,12079.99,4,3,5,435,Big Spenders
10,12358.0,10.0,3,2719.01,5,3,5,535,Big Spenders
11,12359.0,60.0,6,2563.36,3,5,5,355,Loyal
12,12360.0,14.0,5,1590.83,5,4,4,544,Champions
13,12361.0,97.0,3,321.35,2,3,2,232,At Risk
14,12362.0,373.0,1,130.00,1,1,1,111,Lost
15,12366.0,268.0,1,500.24,1,1,2,112,Lost
16,12368.0,263.0,1,917.70,1,1,3,113,Lost
17,12369.0,48.0,3,1791.15,3,3,4,334,Big Spenders
18,12370.0,259.0,3,774.62,1,3,3,133,At Risk
19,12371.0,44.0,3,2179.42,3,3,5,335,Big Spenders
20,12373.0,259.0,2,763.05,1,3,3,133,At Risk
21,12374.0,56.0,3,2246.29,3,3,5,335,Big Spenders
22,12376.0,24.0,2,503.15,4,3,2,432,Need Attention
23,12377.0,16.0,2,1798.20,4,3,4,434,Big Spenders
24,12378.0,197.0,1,1407.70,1,1,4,114,Big Spenders
25,12379.0,57.0,2,767.98,3,3,3,333,Need Attention
26,12380.0,100.0,7,6951.49,2,5,5,255,Big Spenders
27,12385.0,14.0,1,1938.40,5,1,4,514,Big Spenders
28,12386.0,1.0,1,258.90,5,1,2,512,Need Attention
29,12387.0,50.0,1,143.94,3,1,1,311,Need Attention
30,12388.0,80.0,2,1120.45,2,3,4,234,Big Spenders
31,12389.0,37.0,3,1433.33,3,3,4,334,Big Spenders
32,12391.0,99.0,5,2312.53,2,4,5,245,Big Spenders
33,12392.0,226.0,1,234.75,1,1,1,111,Lost
34,12393.0,17.0,2,816.85,4,3,3,433,Need Attention
35,12395.0,6.0,4,2048.64,5,4,4,544,Champions
36,12396.0,309.0,1,931.43,1,1,3,113,Lost
37,12399.0,20.0,3,853.65,4,3,3,433,Need Attention
38,12400.0,49.0,1,205.25,3,1,1,311,Need Attention
39,12402.0,27.0,5,1031.30,4,4,4,444,Champions
40,12403.0,156.0,1,591.66,2,1,3,213,Lost
41,12404.0,317.0,1,63.24,1,1,1,111,Lost
42,12406.0,34.0,3,2975.06,4,3,5,435,Big Spenders
43,12408.0,20.0,3,1452.22,4,3,4,434,Big Spenders
44,12409.0,55.0,4,12346.62,3,4,5,345,Loyal
45,12410.0,137.0,1,320.38,2,1,2,212,Lost
46,12411.0,44.0,1,346.90,3,1,2,312,Need Attention
47,12412.0,37.0,3,1370.05,3,3,4,334,Big Spenders
48,12413.0,37.0,1,241.35,3,1,1,311,Need Attention
49,12414.0,98.0,3,390.00,2,3,2,232,At Risk

Now let us visualize the segmented groups:

In [ ]:
segment_summary = RFM.groupby('Segment').agg({
    'CustomerID': 'count',
    'Recency_Days': 'mean',
    'Frequency': 'mean',
    'Monetary': 'mean'
}).rename(columns={'CustomerID':'Count'}).sort_values('Count', ascending=False)

display(segment_summary)

                Count  Recency_Days  Frequency     Monetary
Segment
Need Attention   1060     32.422642   1.719811   429.827076
Champions         895     12.165363  11.878212  6292.950219
Lost              867    218.683968   1.000000   265.761848
Big Spenders      600     98.338333   3.690000  2370.944305
At Risk           502    159.061753   2.631474   528.721375
Loyal             390     40.320513   6.048718  2117.425364